### ISSUE TITLE
Existing API in standard lib

### ISSUE THREAD

**Issue by thosakwe** [axetroy/protocols#1]
Hi, nice library! I just wanted to let you know the Dart standard library already has a similar, if not identical, functionality. Example:

```dart
var uri = Uri.parse("http://www.google.com");
print(uri.scheme); // 'http'
```

**Comment by axetroy** [comment]
Thanks for telling me that.
i try it just before, think It can not meet my needs.
such this:

```dart
var uri1 = Uri.parse('https://github.com/axetroy/protocols.git');
print(uri1.scheme); // 'https'

var uri2 = Uri.parse('git@github.com:axetroy/protocols.git');
print(uri2.scheme); // throw error
```

actually, it just not only parse the URL but also git address

**Comment by thosakwe** [comment]
Oh, I see. Great!
